using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace Gold.Core.Vendors
{
    /// <summary>
    /// Represents a User
    /// </summary>
    public class User5
    {
        /// <summary>
        /// DB id
        /// </summary>
        public Guid UserId { get; set; }
        /// <summary>
        /// Role of the user
        /// </summary>
        public string Role { get; set; }
        /// <summary>
        /// First name (also middle name)
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// Family name
        /// </summary>
        public string FamilyName { get; set; }
        /// <summary>
        /// Email address
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Mobile number
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// GOLD balance
        /// </summary>
        public decimal Balance { get; set; }
        /// <summary>
        /// IBAN of the user
        /// </summary>
        public string IBAN { get; set; }
        /// <summary>
        /// Member id generated by goldtag
        /// </summary>
        public int MemberId { get; set; }
        /// <summary>
        /// If true user can be considered lvl 1 (old system)
        /// </summary>
        public bool Verified { get; set; }
        /// <summary>
        /// Blocked gold grams
        /// </summary>
        public decimal? BlockedGrams { get; set; }



        private User5() { }

        
        /// <summary>
        /// Changes the Balance of the user
        /// </summary>
        /// <param name="value">Can be either negtive or positive value</param>
        public void ManipulateBalance(decimal value)
        {
            Balance += value;
        }


    }
}
