using System;
using System.Collections.Generic;
using System.Text;

namespace Gold.Core.Vendors
{
    /// <summary>
    /// Represents a 3rd party Vendor
    /// </summary>
    public class Vendor
    {
        /// <summary>
        /// DB id
        /// </summary>
        public Guid VendorId { get; set; }
        /// <summary>
        /// Common name of the vendor (for example Paycell)
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// Contact Email
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Contact phone
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// Api key generated by Goldtag
        /// </summary>
        public string ApiKey { get; set; }
        /// <summary>
        /// Secret firstly generated then can be changed by vendor
        /// </summary>
        public string Secret { get; set; }
        /// <summary>
        /// Vendor Gold Balance
        /// </summary>
        public decimal Balance { get; set; }
        /// <summary>
        /// Vendor silver balance, can be null
        /// </summary>
        public decimal? SilverBalance { get; set; }

        private Vendor() { }

        /// <summary>
        /// Creates new Vendor
        /// </summary>
        /// <param name="name">Name of vendor</param>
        /// <param name="email">contact mail</param>
        /// <param name="phone">contact phone</param>
        /// <param name="apikey">first api key</param>
        /// <param name="secret">first secret</param>
        public Vendor(string name, string email, string phone, string apikey, string secret)
        {
            Name = name;
            Email = email;
            Phone = phone;
            ApiKey = apikey;
            Secret = secret;
            Balance = 0.00M;
            SilverBalance = 0.00M;
        }



        
    }
}
