using System;
using System.Globalization;

namespace Gold.Core.Version2
{
    /// <summary>
    /// represents a registration attempt for membership
    /// </summary>
    public class UserRegistration
    {
        /// <summary>
        /// db id
        /// </summary>
        public Guid UserId { get; set; }
        /// <summary>
        /// First name (also middle name)
        /// </summary>
        public string FirstName { get; set; }
        /// <summary>
        /// Family name
        /// </summary>
        public string FamilyName { get; set; }
        /// <summary>
        /// Date of birth
        /// </summary>
        public DateTime Birthdate { get; set; }
        /// <summary>
        /// Email address
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// Password of the user
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// Mobile number
        /// </summary>
        public string Phone { get; set; }
        /// <summary>
        /// Member id generated by goldtag
        /// </summary>
        public int MemberId { get; set; }
        /// <summary>
        /// If true then user must complete SmS validation
        /// </summary>
        public bool Banned { get; set; }
        /// <summary>
        /// Special comments by admins (to be used for banning etc.)
        /// </summary>
        public string AdminNotes { get; set; }
        /// <summary>
        /// User register time and date
        /// </summary>
        public DateTime DateCreated { get; set; }
        /// <summary>
        /// sms verify code
        /// </summary>
        public int VerificationCode { get; set; }
       
        private UserRegistration() { }

        /// <summary>
        /// creates new registration attempt
        /// </summary>
        /// <param name="memberId">id</param>
        /// <param name="firstName">first name</param>
        /// <param name="familyName">sirname</param>
        /// <param name="pass">password</param>
        /// <param name="phone">mobile num</param>
        /// <param name="birthDate">date of birth</param>
        /// <param name="code">verify code</param>
        public UserRegistration(int memberId, 
                    string firstName, string familyName,
                    string pass, string phone, string birthDate, int code)
        {

            MemberId = memberId;
            FirstName = firstName;
            FamilyName = familyName;
            
            Password = pass;
            
            Phone = phone;
            Birthdate = DateTime.ParseExact(birthDate, "yyyy-MM-dd", CultureInfo.InvariantCulture);
            
            Banned = true;
            
            DateCreated = DateTime.Now;
            VerificationCode = code;
        }    

        /// <summary>
        /// bans the user
        /// </summary>
        /// <param name="reason">with reason</param>
        public void PermanentlyBanUser(string reason)
        {
            Banned = true;
            AdminNotes = (AdminNotes != null) ? AdminNotes += ":" + reason : reason;
        }

        /// <summary>
        /// lifts ban
        /// </summary>
        /// <param name="reason">lift param>
        public void LiftUserBan(string reason)
        {
            Banned = false;
            AdminNotes = (AdminNotes != null) ? AdminNotes += ":" + reason : reason;

        }

    }
}
